name: CI

on:
  push:
    branches:
      - ft/automation_with_github_action
#  pull_request:
#    branches:
#      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Change to your required Java version
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{runner.os}}-maven-${{hashFiles('**/pom.xml')}}
          restore-keys: ${{runner.os}}-maven

      - name: Build and package
        run: mvn clean package

      - name: List the contents of the target directory
        run: ls -la target

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t adkodjane/github-action-demo:latest .
          docker images

      - name: Push Docker image
        run: |
          docker push adkodjane/github-action-demo:latest
          docker push adkodjane/github-action-demo:${{ github.sha }}